/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Answers {
  content: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  question_id: string | null;
  related_chunk_ids: string[] | null;
}

export interface Chunks {
  content: string;
  created_at: Generated<Timestamp | null>;
  embedding: string | null;
  speaker: string;
  id: Generated<string>;
  token_count: number | null;
  transcript_id: string | null;
  position: number | null;
  strategy: string;
}

export interface Conversations {
  id: Generated<string>;
  patient_id: string | null;
  started_at: Generated<Timestamp | null>;
  transcript_id: string | null;
}

export interface Messages {
  content: string;
  conversation_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  message_type: Generated<string>;
  sender: string;
}

export interface Migrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface Patients {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string;
}

export interface Questions {
  content: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  transcript_id: string | null;
}

export interface Transcripts {
  created_at: Generated<Timestamp | null>;
  full_text: string;
  id: Generated<string>;
  patient_id: string | null;
  title: string | null;
}

export interface Users {
  email: string;
  id: Generated<number>;
  name: string;
}

export interface DB {
  answers: Answers;
  chunks: Chunks;
  conversations: Conversations;
  messages: Messages;
  migrations: Migrations;
  patients: Patients;
  questions: Questions;
  transcripts: Transcripts;
  users: Users;
}
